// @ts-check

/**
 * Sidebar for the CyberRack section, a second docs instance separate from the
 * course. Kept apart on purpose: the course runs on a laptop and requires no
 * hardware purchase, and nothing here should ever read as a prerequisite.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  cyberrackSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
