// @ts-check

/**
 * Sidebar for the Drills section, a third docs instance.
 *
 * Structured as a docs instance from the start rather than a single page, so
 * that adding modules and submodules later is adding files rather than
 * restructuring URLs. Autogenerated, so the sidebar grows on its own.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  drillsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
